version: '3.8'

services:
  backend:
    container_name: backend
    build: NoruBannerAPI/
    ports:
      - 5000:80
    depends_on:
      - redis_img
    restart: always
    links:
      - redis_img

  client:
    container_name: client
    build: client-app/
    ports:
      - 3000:80
    depends_on:
      - backend
    restart: always

  redis_img:
    container_name: redis_img
    image: redis
    ports:
      - 6379:6379
    restart: always